# Change these first
owner: cake-tech # Your GitHub organization or username, where this repository lives
repo: upptime-cakewallet # The name of this repository

sites:
  - name: cakewallet.com
    url: https://cakewallet.com
    icon: https://cakewallet.com/assets/images/logo/Cake%20Wallet%20Logo%202021_App%20Icon.png
    asignees:
      - samsunggalaxyplayer
  - name: monero.com
    url: https://monero.com
    icon: https://i.imgur.com/WxsaoFP.png
    assignees:
      - tannerdsilva
  - name: buy.cakepay.com
    url: https://buy.cakepay.com
    icon: https://cakewallet.com/assets/images/logo/Cake%20Wallet%20Logo%202021_App%20Icon.png
    assignees:
      - tannerdsilva
  - name: xmr-node.cakewallet.com:18081
    check: "tcp-ping"
    url: xmr-node.cakewallet.com
    port: 18081
    icon: https://i.imgur.com/Pr74gsI.png
    assignees:
      - tannerdsilva
  - name: electrum.cakewallet.com:50002
    check: "tcp-ping"
    url: electrum.cakewallet.com
    port: 50002
    icon: https://upload.wikimedia.org/wikipedia/commons/4/46/Bitcoin.svg
    assignees:
      - tannerdsilva
  - name: ltc-electrum.cakewallet.com:50002
    check: "tcp-ping"
    url: ltc-electrum.cakewallet.com
    port: 50002
    icon: https://upload.wikimedia.org/wikipedia/commons/f/f8/LTC-400.png
    assignees:
      - tannerdsilva
  - name: cakexmrl7bonq7ovjka5kuwuyd3f7qnkz6z6s6dmsy3uckwra7bvggyd.onion:18081
    check: "tcp-ping"
    url: $XMR_ONION
    port: 18081
    icon: https://i.imgur.com/Pr74gsI.png
    assignees:
      - tannerdsilva
  - name: XMR Asia Servers
    check: "tcp-ping"
    url: $XMR_ASIA
    port: 18081
    icon: https://i.imgur.com/Pr74gsI.png
    assignees:
      - tannerdsilva
  - name: XMR EU Servers
    check: "tcp-ping"
    url: $XMR_EU
    port: 18081
    icon: https://i.imgur.com/Pr74gsI.png
    assignees:
      - tannerdsilva
  - name: XMR USA Servers
    check: "tcp-ping"
    url: $XMR_USA
    port: 18081
    icon: https://i.imgur.com/Pr74gsI.png
    assignees:
      - tannerdsilva

assignees:


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cakewallet.com
  # baseUrl: /upptime-cakewallet
  logoUrl: https://cakewallet.com/assets/images/logo/Cake%20Wallet%20Logo%202021_App%20Icon.png
  favicon: https://cakewallet.com/assets/images/logo/Cake%20Wallet%20Logo%202021_App%20Icon.png
  name: Cake Wallet Status
  introTitle: "Cake Wallet Service Status"
  introMessage: Service status is updated approximately every 5-30 minutes. Charts are updated less frequently.
  theme: light
  navbar:
    - title: Twitter
      href: https://twitter.com/cakewallet
    - title: Email Support
      href: mailto:support@cakewallet.com
    - title: Telegram Support
      href: https://t.me/cakewallet_bot

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
