# Change these first
owner: cake-tech # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: cakewallet.com
    url: https://cakewallet.com
    icon: /assets/logo.ico
  - name: monero.com
    url: https://monero.com
    icon: /assets/logo.ico
  - name: xmr-node.cakewallet.com
    check: "tcp-ping"
    url: xmr-node.cakewallet.com
    port: 18081
    icon: /assets/logo.ico
  - name: electrum.cakewallet.com
    check: "tcp-ping"
    url: electrum.cakewallet.com
    port: 50002
    icon: /assets/logo.ico
  - name: ltc-electrum.cakewallet.com
    check: "tcp-ping"
    url: ltc-electrum.cakewallet.com
    port: 50002
    icon: /assets/logo.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://cakewallet.com/assets/images/logo/Cake%20Wallet%20Logo%202021_App%20Icon.png
  favicon: 
  name: Cake Wallet Nodes
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a work in progress page.
  theme: light
  navbar:
    - title: Twitter
      href: https://twitter.com/cakewallet
    - title: Email Support
      href: mailto:support@cakewallet.com
    - title: Telegram Support
      href: https://t.me/cakewallet_bot

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
