# Change these first
owner: cake-tech # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: cakewallet.com
    url: https://cakewallet.com
    icon: https://cakewallet.com/assets/images/logo/Cake%20Wallet%20Logo%202021_App%20Icon.png
  - name: monero.com
    url: https://monero.com
    icon: /assets/monerocom.png
  - name: xmr-node.cakewallet.com
    check: "tcp-ping"
    url: xmr-node.cakewallet.com
    port: 18081
    icon: /assets/monero.png
  - name: electrum.cakewallet.com
    check: "tcp-ping"
    url: electrum.cakewallet.com
    port: 50002
    icon: /assets/bitcoin.png
  - name: ltc-electrum.cakewallet.com
    check: "tcp-ping"
    url: ltc-electrum.cakewallet.com
    port: 50002
    icon: /assets/litecoin.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://cakewallet.com/assets/images/logo/Cake%20Wallet%20Logo%202021_App%20Icon.png
  favicon: https://cakewallet.com/assets/images/logo/Cake%20Wallet%20Logo%202021_App%20Icon.png
  name: Cake Wallet Status
  introTitle: "Cake Wallet Service Status"
  introMessage: Service status is updated approximately every 5-10 minutes.
  theme: light
  navbar:
    - title: Twitter
      href: https://twitter.com/cakewallet
    - title: Email Support
      href: mailto:support@cakewallet.com
    - title: Telegram Support
      href: https://t.me/cakewallet_bot

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
